on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - run: mvn compile test
      - name: Publish
        run: mvn -e deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MAVEN_SETTINGS_B64: ${{ secrets.MAVEN_SETTINGS }}
          MAVEN_SETTINGS_SECURITY_B64: ${{ secrets.MAVEN_SECURITY }}
          MAVEN_P12_B64: ${{ secrets.MAVEN_P12 }}
          MAVEN_P12_PASSWORD: ${{ secrets.MAVEN_P12_PASSWORD }}
          ROOTCA_B64: ${{ secrets.CACERT }}