on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          java-version: 13
          distribution: 'zulu'
      - run: mvn compile test
