on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 13
          distribution: 'zulu'
      - name: Set up Maven  
        uses: tradeshift/actions-setup-maven@v4.4
        with:
          maven-version: 3.6.3
      - name: Configure maven
        uses: tradeshift/actions-setup-java-mtls@debug
        with:
          java-version: "${{ steps.setupJava.outputs.version }}"
          maven-settings: ${{ secrets.MAVEN_SETTINGS }}
          maven-security: ${{ secrets.MAVEN_SECURITY }}
          maven-p12: ${{ secrets.MAVEN_P12 }}
          maven-p12-password: ${{ secrets.MAVEN_P12_PASSWORD }}
          mtls-cacert: ${{ secrets.MTLS_CACERT }}
      - run: mvn compile test
          - name: Set up Maven
        uses: tradeshift/actions-setup-maven@v4.4
        with:
          maven-version: 3.6.3
      - name: Configure maven
        uses: tradeshift/actions-setup-java-mtls@v1
        with:
          java-version: "${{ steps.setupJava.outputs.version }}"
          maven-settings: ${{ secrets.MAVEN_SETTINGS }}
          maven-security: ${{ secrets.MAVEN_SECURITY }}
          maven-p12: ${{ secrets.MAVEN_P12 }}
          maven-p12-password: ${{ secrets.MAVEN_P12_PASSWORD }}
          mtls-cacert: ${{ secrets.MTLS_CACERT }}